# Generated by Django 4.2.7 on 2026-02-08 15:36

import apps.materials.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=apps.materials.models.tenant_material_upload_path)),
                ('file_type', models.CharField(choices=[('AUDIO', 'Audio'), ('PDF', 'PDF'), ('DOCX', 'DOCX'), ('IMAGE', 'Image'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('created_by_id', models.BigIntegerField(blank=True, db_index=True, help_text='ID of the user (User) who uploaded this material in the public schema', null=True)),
                ('is_public', models.BooleanField(default=False, help_text='If True, visible to ALL students in center. If False, only assigned groups/students can access.')),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups that have access to this material (if not public).', related_name='materials', to='groups.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
