# Generated by Django 4.2.7 on 2026-02-07 15:36

import apps.core.utils
import apps.core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='center_avatars/')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('schema_name', models.CharField(blank=True, help_text='PostgreSQL schema name for this tenant (auto-generated from slug)', max_length=63, null=True, unique=True, validators=[apps.core.validators.validate_schema_name])),
                ('is_ready', models.BooleanField(default=False, help_text='True when tenant schema is fully migrated and ready for use.')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='contact email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('primary_color', models.CharField(default='#FFA500', max_length=7)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], db_index=True, default='TRIAL', max_length=20, verbose_name='status')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='trial ends at')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('plan', models.CharField(choices=[('FREE', 'Free Trial'), ('BASIC', 'Basic'), ('PRO', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='subscription starts at')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='subscription ends at')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='centers.center')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(default=apps.core.utils.generate_code, max_length=12, unique=True)),
                ('role', models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('GUEST', 'Guest Student')], max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('is_guest', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_invitations', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='centers.center')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('center_name', models.CharField(help_text='Name of the center they want to join', max_length=200)),
                ('full_name', models.CharField(help_text='Full name of the person requesting', max_length=150)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=20)),
                ('message', models.TextField(help_text='Message from the requester')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONTACTED', 'Contacted'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['center_name', 'phone_number'], name='centers_con_center__630ec9_idx'), models.Index(fields=['status', 'created_at'], name='centers_con_status_c5271a_idx')],
            },
        ),
    ]
