"""
Analytics Models - Progress tracking and statistics
"""
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.core.models import TenantBaseModel


class StudentProgress(TenantBaseModel):
    """
    Aggregated Student Progress Tracking
    Real-time dashboard data
    """
    
    student = models.OneToOneField(
        'authentication.User',
        on_delete=models.CASCADE,
        related_name='progress',
        limit_choices_to={'role': 'STUDENT'}
    )
    
    # Overall Statistics
    total_attempts = models.PositiveIntegerField(_('total attempts'), default=0)
    completed_attempts = models.PositiveIntegerField(_('completed attempts'), default=0)
    in_progress_attempts = models.PositiveIntegerField(_('in progress attempts'), default=0)
    
    average_score = models.DecimalField(
        _('average score'),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    highest_score = models.PositiveIntegerField(_('highest score'), default=0)
    lowest_score = models.PositiveIntegerField(_('lowest score'), default=0)
    
    pass_rate = models.DecimalField(
        _('pass rate (%)'),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    
    # Level-specific Statistics
    n5_average = models.DecimalField(
        _('N5 average'),
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True
    )
    n5_attempts = models.PositiveIntegerField(_('N5 attempts'), default=0)
    
    n4_average = models.DecimalField(
        _('N4 average'),
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True
    )
    n4_attempts = models.PositiveIntegerField(_('N4 attempts'), default=0)
    
    n3_average = models.DecimalField(
        _('N3 average'),
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True
    )
    n3_attempts = models.PositiveIntegerField(_('N3 attempts'), default=0)
    
    n2_average = models.DecimalField(
        _('N2 average'),
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True
    )
    n2_attempts = models.PositiveIntegerField(_('N2 attempts'), default=0)
    
    n1_average = models.DecimalField(
        _('N1 average'),
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True
    )
    n1_attempts = models.PositiveIntegerField(_('N1 attempts'), default=0)
    
    # Section Averages (across all tests)
    moji_goi_average = models.DecimalField(
        _('vocabulary average'),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    bunpou_average = models.DecimalField(
        _('grammar average'),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    dokkai_average = models.DecimalField(
        _('reading average'),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    choukai_average = models.DecimalField(
        _('listening average'),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    
    # Timing Analytics
    average_completion_time_minutes = models.PositiveIntegerField(
        _('average completion time (minutes)'),
        default=0
    )
    total_study_time_hours = models.DecimalField(
        _('total study time (hours)'),
        max_digits=10,
        decimal_places=2,
        default=0
    )
    
    # Activity Tracking
    last_attempt_date = models.DateTimeField(_('last attempt date'), null=True, blank=True)
    first_attempt_date = models.DateTimeField(_('first attempt date'), null=True, blank=True)
    streak_days = models.PositiveIntegerField(
        _('streak days'),
        default=0,
        help_text=_('Consecutive days with activity')
    )
    
    # Weak areas (JSON storing mondai types with low scores)
    weak_areas = models.JSONField(
        _('weak areas'),
        default=list,
        blank=True,
        help_text=_('Areas where student needs improvement')
    )
    
    class Meta:
        db_table = 'student_progress'
        verbose_name = _('student progress')
        verbose_name_plural = _('student progress')
        indexes = [
            models.Index(fields=['organization_id', 'average_score']),
            models.Index(fields=['last_attempt_date']),
        ]
    
    def __str__(self):
        return f"Progress: {self.student.get_full_name()}"


class OrganizationAnalytics(TenantBaseModel):
    """
    Daily Organization-level Analytics
    Generated by periodic Celery task
    """
    
    date = models.DateField(_('date'), db_index=True)
    
    # User Statistics
    total_students = models.PositiveIntegerField(_('total students'), default=0)
    active_students_today = models.PositiveIntegerField(_('active students today'), default=0)
    active_students_week = models.PositiveIntegerField(
        _('active students (7 days)'),
        default=0
    )
    active_students_month = models.PositiveIntegerField(
        _('active students (30 days)'),
        default=0
    )
    
    total_teachers = models.PositiveIntegerField(_('total teachers'), default=0)
    active_teachers = models.PositiveIntegerField(_('active teachers'), default=0)
    
    total_groups = models.PositiveIntegerField(_('total groups'), default=0)
    active_groups = models.PositiveIntegerField(_('active groups'), default=0)
    
    # Test Statistics
    total_mock_tests = models.PositiveIntegerField(_('total mock tests'), default=0)
    published_mock_tests = models.PositiveIntegerField(_('published mock tests'), default=0)
    
    total_assignments = models.PositiveIntegerField(_('total assignments'), default=0)
    active_assignments = models.PositiveIntegerField(_('active assignments'), default=0)
    
    # Attempt Statistics
    attempts_today = models.PositiveIntegerField(_('attempts today'), default=0)
    attempts_completed_today = models.PositiveIntegerField(
        _('attempts completed today'),
        default=0
    )
    attempts_in_progress = models.PositiveIntegerField(_('attempts in progress'), default=0)
    
    # Performance Metrics
    average_score_today = models.DecimalField(
        _('average score today'),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    average_score_week = models.DecimalField(
        _('average score (7 days)'),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    average_score_month = models.DecimalField(
        _('average score (30 days)'),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    
    pass_rate_today = models.DecimalField(
        _('pass rate today (%)'),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    pass_rate_week = models.DecimalField(
        _('pass rate (7 days) (%)'),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    pass_rate_month = models.DecimalField(
        _('pass rate (30 days) (%)'),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    
    # Level Distribution
    n5_students = models.PositiveIntegerField(_('N5 students'), default=0)
    n4_students = models.PositiveIntegerField(_('N4 students'), default=0)
    n3_students = models.PositiveIntegerField(_('N3 students'), default=0)
    n2_students = models.PositiveIntegerField(_('N2 students'), default=0)
    n1_students = models.PositiveIntegerField(_('N1 students'), default=0)
    
    # Storage usage
    storage_used_mb = models.PositiveIntegerField(
        _('storage used (MB)'),
        default=0
    )
    
    class Meta:
        db_table = 'organization_analytics'
        verbose_name = _('organization analytics')
        verbose_name_plural = _('organization analytics')
        ordering = ['-date']
        unique_together = [['organization_id', 'date']]
        indexes = [
            models.Index(fields=['organization_id', '-date']),
        ]
    
    def __str__(self):
        return f"Analytics for {self.organization_id} on {self.date}"


class TeacherAnalytics(TenantBaseModel):
    """
    Teacher performance analytics
    """
    
    teacher = models.OneToOneField(
        'authentication.User',
        on_delete=models.CASCADE,
        related_name='teacher_analytics',
        limit_choices_to={'role': 'TEACHER'}
    )
    
    # Test Creation
    total_tests_created = models.PositiveIntegerField(_('tests created'), default=0)
    published_tests = models.PositiveIntegerField(_('published tests'), default=0)
    
    # Assignments
    total_assignments = models.PositiveIntegerField(_('total assignments'), default=0)
    total_students_taught = models.PositiveIntegerField(_('students taught'), default=0)
    
    # Student Performance (under this teacher)
    average_student_score = models.DecimalField(
        _('average student score'),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    student_pass_rate = models.DecimalField(
        _('student pass rate (%)'),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    
    # Feedback given
    feedbacks_given = models.PositiveIntegerField(_('feedbacks given'), default=0)
    
    # Activity
    last_activity_date = models.DateTimeField(_('last activity'), null=True, blank=True)
    
    class Meta:
        db_table = 'teacher_analytics'
        verbose_name = _('teacher analytics')
        verbose_name_plural = _('teacher analytics')
    
    def __str__(self):
        return f"Analytics: {self.teacher.get_full_name()}"