# Generated by Django 4.2.7 on 2026-02-08 15:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('max_students', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('teacher_count', models.PositiveIntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='group_avatars/')),
            ],
            options={
                'db_table': 'groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('role_in_group', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], max_length=20)),
                ('joined_at', models.DateTimeField()),
                ('left_at', models.DateTimeField()),
                ('left_reason', models.CharField(choices=[('MOVED', 'Moved to another group'), ('REMOVED', 'Removed by admin'), ('LEFT', 'Left voluntarily')], max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to='groups.group')),
            ],
            options={
                'db_table': 'groupmembershiphistory',
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('role_in_group', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
            ],
            options={
                'db_table': 'groupmembership',
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_group_name'),
        ),
        migrations.AddIndex(
            model_name='groupmembershiphistory',
            index=models.Index(fields=['user_id', 'left_at'], name='groupmember_user_id_c5e005_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembershiphistory',
            index=models.Index(fields=['group', 'left_at'], name='groupmember_group_i_01a9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user_id', 'group', 'role_in_group'], name='groupmember_user_id_e5d266_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user_id', 'role_in_group'], name='groupmember_user_id_e0495d_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'role_in_group'], name='groupmember_group_i_66705c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('user_id', 'group', 'role_in_group')},
        ),
    ]
