# Generated by Django 4.2.7 on 2025-12-06 15:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='organization name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('country', models.CharField(default='Uzbekistan', max_length=100, verbose_name='country')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/', verbose_name='logo')),
                ('primary_color', models.CharField(default='#1a73e8', max_length=7, verbose_name='primary color')),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], db_index=True, default='TRIAL', max_length=20, verbose_name='status')),
                ('max_students', models.PositiveIntegerField(default=50, verbose_name='max students')),
                ('max_teachers', models.PositiveIntegerField(default=5, verbose_name='max teachers')),
                ('max_storage_mb', models.PositiveIntegerField(default=1000, verbose_name='max storage (MB)')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='trial ends at')),
                ('subscription_starts_at', models.DateTimeField(blank=True, null=True, verbose_name='subscription starts')),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='subscription ends')),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=50, verbose_name='timezone')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='default language')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='enabled features')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', 'Only lowercase letters, numbers, and underscores.')], verbose_name='schema name')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(choices=[('FREE', 'Free Trial'), ('BASIC', 'Basic'), ('PRO', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20, verbose_name='plan')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='billing cycle')),
                ('next_billing_date', models.DateField(blank=True, null=True, verbose_name='next billing date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='auto renew')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'subscriptions',
            },
        ),
    ]
